module.exports = {
	testEnvironment: 'node',
	coverageDirectory: 'coverage',
	coverageReporters: ['text', 'lcov', 'clover', 'json-summary'],
	collectCoverageFrom: [
		'utils/**/*.js',
		'services/**/*.js',
		'shared/**/*.js',
		'interactions/**/*.js',
		'commands/**/*.js',
		'events/**/*.js',
		'data/models/**/*.js',
		'scripts/lib/wiki-sync/**/*.js',
		'scripts/lib/migrate-v2/**/*.js',
		'.dashboard/auth.js',
		'.dashboard/lib/**/*.js',
		'.dashboard/server.js',
		'!**/node_modules/**',
		'!**/coverage/**',
		'!**/__tests__/**',
	],
	testMatch: [
		'**/__tests__/**/*.test.js',
		'**/?(*.)+(spec|test).js',
	],
	coverageThreshold: {
		global: {
			branches: 90,
			functions: 90,
			lines: 90,
			statements: 90,
		},
	},
	setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
	verbose: true,
};
